import 'package:flutter/material.dart';
class DetailsScreen extends StatelessWidget {
   bool isContentVi;
   bool isContentVi2;
   bool isContentVi3;
  DetailsScreen({required this.isContentVi,required this.isContentVi2,required this.isContentVi3});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Recipes'),
        backgroundColor: Colors.black87,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(40),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
          Visibility(
          visible: isContentVi,
          child: Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text('Palak Paneer',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
              SizedBox(height:10),
              Text('Palak paneer is one of our favorite Indian takeout dishes, so the first time we made it, we felt a bit intimidated to give it a go at home. We have now been making and perfecting this spinach curry recipe for years as it has become our go-to easy comfort food dinner. We love that it is delicious and easy to make with only fresh ingredients (and tons of spinach) so it is healthier, too!Fresh spinach, tomatoes, aromatics, herbs, and spices make the base of this delicious Indian dish. We use whipping cream to add creaminess to the gravy and top it with pan-seared paneer. Serve this easy stove-top dinner with naan and basmati rice for an irresistible authentic-tasting meal!',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:15),
              Text('Palak Paneer Recipe',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('Ingredients:',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('8 ounces (250g) curly spinach leaves\n3 tablespoons (45g) ghee or neutral-flavored oil, like sunflower, divided\n8 ounces (250g) paneer, cut into small rectangles \n1 teaspoon cumin seeds\n1/2 teaspoon black mustard seeds\n3 medium garlic cloves, finely chopped\n1/2 teaspoon chile powder, such as Kashmiri\n1 teaspoon (3g) Diamond Crystal kosher salt; if using table salt, use half as much by volume or same weight\n2 tablespoons (30ml) heavy cream',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:10),
              Text('Directions',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
              SizedBox(height:5),
              Text('Step 1: Get the Palak Puree',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('First, boil palak for a few minutes. Don’t over boil it to prevent its leaves from turning black. Just boil it for a few minutes to retain the green colour of the leaves.Once it’s properly boiled, it’s time to strain it. Now take the strained leaves of palak in a bowl and add some ice cold water to it. This is how to make palak paneer green, as it helps in preserving the green colour of the palak leaves. Drain the ice-cold water and put spinach into a mixer to make palak puree. There is no need to add extra cup water to make palak puree. Once the puree is made, keep it aside.',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
              SizedBox(height:5),
              Text('Step 2: Prepare the masala',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('Take a pan and put 2 tbsp desi ghee into it and heat. Make sure ghee is allowed to melt in low flame to ensure it doesn’t turn brown. Now add chopped garlic and ginger and saute them for a while. Now, add onions and let them turn a little brown. Once the onions are brown, put green chilli and finely chopped tomato into the pan. After that, add 1 tablespoon degi mirch (red chilli), half tablespoon turmeric and some salt to soften tomatoes.',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
              SizedBox(height:5),
              Text('Step 3: Add palak puree and cook well',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('Now, add the palak puree to the masala and stir well. Keep simmering the palak gravy until the water evaporates and palak is properly cooked. Now add some milk to the palak puree. Milk is added to tone down the bitterness of green palak leaves. Now keep stirring it until the milk absorbs into the palak puree. Also, season it with salt, degi mirch, kitchen king, garam masala, kasuri methi and dhaniya powder. Finally, add some butter to the mixture to enhance its taste.',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
              SizedBox(height:5),
              Text('Step 4: Add paneer cubes to cooked palak masala',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('Now, add about 150 gms of palak cubes to the palak. Stir gently again to let paneer absorb the masala while maintaining the uniform consistency of the gravy. Lastly, add some cream to the mixture to enhance its taste while giving a good texture to the dish.',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
              SizedBox(height:5),
              Text('Step 5: Serve and enjoy',
                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
              SizedBox(height:3),
              Text('Now take out the dish into a bowl. Garnish it with vertically cut ginger and some cream. Serve it piping hot with some roti, parantha, naan or jeera rice.',
                  style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
            ],
    ),
          ),
          ),
    Visibility(
    visible: isContentVi2,
    child: Container(

    child: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text('Chole Bhature',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
        SizedBox(height:10),
        Text('Chole Bhature also known as Chana Bhatura is one of the most popular Punjabi dish liked almost all over India. Chana Bhatura is a spicy, tasty and a filling dish.Chole stands for a spiced tangy chickpea curry and Bhatura is a soft and fluffy fried leavened bread. Chola Bhatura always make for a delicious and filling meal.The delicious chickpea curry can be also had with poori, Naan or Kulcha or Aloo Kulcha or Aloo Paratha. They taste equally good with bread or pav.',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:15),
        Text('Chole Bhature Recipe',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Ingredients:',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Chickpeas (kabuli chana) soaked overnight and drained 1 cup\nTea bags 2\nSalt to taste\nGhee 2 tablespoons\nCumin seeds 1 teaspoon\nGreen chillies slit\nGinger-green chilli paste 1 tablespoon\nCoriander powder 1 tablespoon\nCumin powder ½ teaspoon\nRed chilli powder 1 teaspoon\nChole masala 1 teaspoon\nDried mango powder ½ teaspoon\nDried pomegranate seeds (anardana) roasted and coarsely crushed 1 tablespoon\nGaram masala powder 1 teaspoon\nFresh coriander sprigs for garnishing\nBhature\nRefined flour (maida) 2½ cups\nBaking powder ½ teaspoon\nBaking soda a pinch\nSalt to taste\nPowdered sugar 2 teaspoons\nYogurt ½ cup\nOil 1 tablespoon + for greasing and to deep fry',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:15),
        Text('Directions',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
        SizedBox(height:5),
        Text('Step 1: Get the chickpeas ready',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Take chickpeas in a pressure cooker. Add tea bags, 6-8 cups water and salt, cover and cook for 15-20 minutes or till fully done and soft. Drain the chickpeas, discard the tea bags and reserve the stock.',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
        SizedBox(height:5),
        Text('Step 2: Prepare the Dough for Bature',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Sieve together flour, baking powder, baking soda, salt and powdered sugar in a parat. Add yogurt and mix well. Add some water and knead into a soft dough. Add 1 tablespoon oil and knead well.Set aside for 15-20 minutes.',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
        SizedBox(height:5),
        Text('Step 3: Prepare the masala	',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Heat ghee in a non-stick pan. Add cumin seeds and green chillies and sauté for 30 seconds. Add ginger-green chilli paste and sauté for 30 seconds. Add coriander powder, cumin powder and chilli powder and mix.Add chole masala and dried mango powder and mix. Add reserved stock, mix and bring mixture to boil.Add boiled chickpeas and ¾ cup water, mix and cook on medium heat for 8-10 minutes. Lightly mash.Add dried pomegranate powder and garam masala powder and mix. Add ¼ cup water. Chop tomatoes, add to pan, mix and cook for 2-3 minutes.',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
        SizedBox(height:5),
        Text('Step 4: Final touch',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Heat sufficient oil in a kadai. Divide the dough into equal portions and shape into balls. Grease worktop with some oil and roll each ball into thick discs.Deep-fry each disc in hot oil till light golden and puffed up. Drain on absorbent paper.',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
        SizedBox(height:5),
        Text('Step 5: Serve and enjoy',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
        SizedBox(height:3),
        Text('Garnish chole with a coriander sprig and serve hot with bhature.',
            style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
      ],
    ),
    ),
    ),
    Visibility(
    visible: isContentVi3,
    child: Container(
    child: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: <Widget>[
      Text('Butter Chicken',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
      SizedBox(height:10),
      Text('Butter chicken, or murgh makhani, is a popular Indian dish that was created by chance in 1947 in Delhi, India when a restaurant mixed together leftover chicken and a creamy tomato sauce. The sauce was made with a mixture of cream and butter, which is why it is known as “Butter Chicken.” The recipe for the sauce combines cream, crushed tomatoes, butter or ghee, onion, garlic, ginger and spices. The spices used include garam masala, turmeric, cumin, coriander and red chili powder. The final dish has a smooth gravy that mild in flavor and slightly sweet. Serve this chicken with a side of grilled garlic naan and basmati rice.',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:15),
      Text('Butter Chicken Recipe',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('Ingredients:',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('2 pounds boneless, skinless chicken thighs cut into bite-sized pieces\n1/2 cup plain yogurt\n1-1/2 tablespoons minced garlic\n1 tablespoon minced fresh ginger\n2 teaspoons garam masala\n1 teaspoon turmeric\n1 teaspoon ground cumin\n1 teaspoon red chili powde\n1 teaspoon salt\n1 tablespoon lemon juice',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:5),
      Text('Sauce:',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('2 tablespoons olive oil\n2 tablespoons ghee\n1 medium onion, minced\n1-1/2 tablespoons garlic, minced\n1 tablespoon ginger, minced\n1-1/2 teaspoons ground cumin\n1-1/2 teaspoons garam masala\n1 teaspoon ground coriander\n1 can (14-1/2 ounces) crushed tomatoes\n1 teaspoon red chili powder\n1-1/4 teaspoons salt\n1 cup heavy whipping cream\n1 tablespoon sugar\n1/2 teaspoon dried fenugreek',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:15),
      Text('Directions',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('Step 1: Marinate the chicken',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('In a large bowl, mix together the yogurt, lemon juice, spices and salt until well combined. Add the chicken thighs and stir well to coat. Cover and let sit for 30 minutes or refrigerate until you are ready to cook. The chicken can marinate for up to 24 hours, but no less than 30 minutes.',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
      SizedBox(height:5),
      Text('Step 2: Sear the chicken',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('Heat the oil in a large skillet over medium heat. Add the chicken, but do not shake off excess yogurt mixture. Sear the chicken to lock in the juices for 2-3 minutes on each side. The chicken does not need to be cooked through as it will finish cooking later in the sauce. Place the chicken into a bowl or on a plate and cover. Set aside.',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
      SizedBox(height:5),
      Text('Step 3: Prepare the sauce',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('Heat ghee in the same skillet. Add the onions and saute until they begin to soften, scraping up any browned bits left from the chicken. Add the ginger and garlic and cook for 1 additional minute. Add the cumin, coriander and garam masala and continue to cook for about 1 minute. Next, add the tomatoes to the skillet, along with the chili powder and salt. Simmer for 10-15 minutes, until the mixture thickens and it has a deep red color. If you have chopped your onion, garlic and ginger finely you can leave the mixture as-is, but if you want a super smooth sauce, spoon the contents of the skillet into a blender and pulse until smooth. If the mixture is too thick, add 1-2 tablespoons of water.',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
      SizedBox(height:5),
      Text('Step 4: Return the chicken to the pan',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('Pour the blended mixture back into the skillet and add in the cream, sugar and fenugreek (if using). Stir the mixture to combine and then add the chicken to the sauce along with its juices. Simmer the chicken for an additional 8-10 minutes, until the chicken is cooked through and the sauce is thick.',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),
      SizedBox(height:5),
      Text('Step 5: Serve the chicken',
          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, fontFamily:'Calibri')),
      SizedBox(height:3),
      Text('Serve the chicken with steamed basmati rice, a sprinkle of cilantro and naan bread.',
          style: const TextStyle(fontWeight: FontWeight.normal, fontSize: 13, fontFamily:'Calibri')),

    ],
    ),
    ),
    ),
          ],
        ),
      ),
    );
  }
}
